"""Data models for the BYS pipeline."""

from __future__ import annotations
from dataclasses import dataclass, field, asdict
from typing import Any
import json
from pathlib import Path

import yaml
from pydantic import BaseModel, Field as PydField


@dataclass
class Lead:
    """Raw lead from targeting."""
    firstName: str
    lastName: str
    companyName: str
    email: str = ""
    linkedinUrl: str = ""
    headline: str = ""
    seniority: str = ""
    industry: str = ""
    techStack: str = ""
    icebreaker: str = ""

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Lead:
        known_fields = {f.name for f in cls.__dataclass_fields__.values()}
        filtered = {k: v for k, v in data.items() if k in known_fields}
        return cls(**filtered)


@dataclass
class EnrichedLead(Lead):
    """Lead enriched with Firecrawl + RapidAPI data."""
    firecrawl_context: dict[str, Any] = field(default_factory=dict)
    linkedin_profile: dict[str, Any] = field(default_factory=dict)
    intent_score: int = 0
    enrichment_errors: list[str] = field(default_factory=list)

    @classmethod
    def from_lead(cls, lead: Lead) -> EnrichedLead:
        return cls(**{k: v for k, v in asdict(lead).items()
                      if k in {f.name for f in Lead.__dataclass_fields__.values()}})


@dataclass
class LeadBrief:
    """Structured analysis of a lead by the Analyst agent."""
    firstName: str
    lastName: str
    companyName: str
    sector: str = ""              # secteur reel (pas juste "SaaS B2B")
    company_moment: str = ""      # ce que vit l'entreprise maintenant
    person_story: str = ""        # parcours et ce qui rend cette personne unique
    person_x_moment: str = ""     # intersection personne x moment
    daily_reality: str = ""       # quotidien concret de cette personne dans son role


@dataclass
class Strategy:
    """Strategic decisions by the Strategist agent."""
    firstName: str
    lastName: str
    angle_type: str = ""          # parcours+momentum, role+news, etc.
    chosen_pain: str = ""         # pain du CAB-P le plus pertinent pour ce lead
    chosen_benefit: str = ""      # benefice a mettre en avant
    information_gap: str = ""     # le gap de curiosite a creer
    key_question: str = ""        # la question qui reste dans la tete
    why_this_angle: str = ""      # justification du choix


@dataclass
class PersonalizedSections:
    """Full personalized emails generated by Claude."""
    firstName: str
    lastName: str
    companyName: str
    email1Subject: str = ""       # subject line email 1
    email1Body: str = ""          # corps complet email 1
    email2Subject: str = ""       # subject line email 2
    email2Body: str = ""          # corps complet email 2
    email3Subject: str = ""       # subject line email 3
    email3Body: str = ""          # corps complet email 3
    linkedinInvite: str = ""      # message d'invite LinkedIn
    linkedinDm: str = ""          # DM LinkedIn apres connexion
    callScript: str = ""          # script d'appel personnalise
    generation_error: str = ""


@dataclass
class InjectionResult:
    """Result of injecting one lead into Lemlist."""
    firstName: str
    lastName: str
    companyName: str
    status: str  # "injected", "excluded", "error"
    lead_id: str = ""
    error_message: str = ""


@dataclass
class InjectionReport:
    """Full report of a batch injection."""
    campaign_id: str
    campaign_name: str
    total: int = 0
    injected: int = 0
    excluded: int = 0
    errors: int = 0
    results: list[InjectionResult] = field(default_factory=list)

    def summary(self) -> str:
        return (
            f"{LOG_PREFIX} Injection: {self.injected}/{self.total} OK, "
            f"{self.excluded} excluded, {self.errors} errors"
        )


class ClientConfig(BaseModel):
    """Client-level configuration from client.yaml."""
    name: str
    date: str
    sender_name: str = ""
    sender_email: str = ""
    sender_title: str = ""
    lemlist_campaign_prefix: str = ""
    model: str = "claude-sonnet-4-6"
    total_budget_usd: float = 50.0
    enrichment: dict = PydField(default_factory=lambda: {
        "providers": ["scrapingdog", "rapidapi_linkedin"],
        "concurrency": 10,
    })

    @classmethod
    def load(cls, client_dir: str | Path) -> ClientConfig:
        path = Path(client_dir) / "client.yaml"
        if not path.exists():
            raise FileNotFoundError(f"client.yaml not found in {client_dir}")
        with open(path) as f:
            return cls(**yaml.safe_load(f))


class CampaignConfig(BaseModel):
    """Campaign-level configuration from campaign.yaml."""
    campaign_id: str
    signal: str = ""
    persona: str = ""
    geo: str = ""
    status: str = "draft"
    channels: list[str] = PydField(default_factory=lambda: ["email", "linkedin"])
    tone: str = "conversationnel, pair-a-pair, curieux"
    custom_rules: list[str] = PydField(default_factory=list)
    banned_words: list[str] = PydField(default_factory=list)
    model: str = "claude-sonnet-4-6"
    concurrency: int = 10
    last_step_at: str | None = None
    error_message: str | None = None

    @classmethod
    def load(cls, campaign_dir: str | Path) -> CampaignConfig:
        path = Path(campaign_dir) / "campaign.yaml"
        if not path.exists():
            raise FileNotFoundError(f"campaign.yaml not found in {campaign_dir}")
        with open(path) as f:
            return cls(**yaml.safe_load(f))

    def save(self, campaign_dir: str | Path) -> None:
        path = Path(campaign_dir) / "campaign.yaml"
        with open(path, "w") as f:
            yaml.dump(self.model_dump(), f, default_flow_style=False, allow_unicode=True)


@dataclass
class CampaignContext:
    """All context needed for a campaign pipeline run."""
    campaign_dir: Path
    client_dir: Path
    campaign_name: str
    leads: list[Lead] = field(default_factory=list)
    ciblage: str = ""
    cab_p: str = ""
    discovery: str = ""
    recap: str = ""
    emails_template: dict[str, Any] = field(default_factory=dict)
    campaign_config: CampaignConfig | None = None
    client_config: ClientConfig | None = None

    @classmethod
    def load(cls, campaign_dir: str | Path) -> CampaignContext:
        """Load campaign context from disk."""
        cdir = Path(campaign_dir)
        client_dir = cdir.parent.parent
        campaign_name = cdir.name

        # Load leads
        leads_file = cdir / "leads.json"
        leads: list[Lead] = []
        if leads_file.exists():
            raw = json.loads(leads_file.read_text())
            leads = [Lead.from_dict(l) for l in raw]

        # Load ciblage
        ciblage = ""
        ciblage_file = cdir / "ciblage.md"
        if ciblage_file.exists():
            ciblage = ciblage_file.read_text()

        # Load CAB-P
        cab_p = ""
        cab_p_file = client_dir / "cab-p.md"
        if cab_p_file.exists():
            cab_p = cab_p_file.read_text()

        # Load discovery
        discovery = ""
        discovery_file = client_dir / "discovery.md"
        if discovery_file.exists():
            discovery = discovery_file.read_text()

        # Load recap
        recap = ""
        recap_file = client_dir / "recap.md"
        if recap_file.exists():
            recap = recap_file.read_text()

        # Load emails template
        emails_template: dict[str, Any] = {}
        emails_file = cdir / "emails.json"
        if emails_file.exists():
            emails_template = json.loads(emails_file.read_text())

        # Load YAML configs (optional — backward compatible)
        campaign_config = None
        campaign_yaml = cdir / "campaign.yaml"
        if campaign_yaml.exists():
            campaign_config = CampaignConfig.load(cdir)

        client_config = None
        client_yaml = client_dir / "client.yaml"
        if client_yaml.exists():
            client_config = ClientConfig.load(client_dir)

        return cls(
            campaign_dir=cdir,
            client_dir=client_dir,
            campaign_name=campaign_name,
            leads=leads,
            ciblage=ciblage,
            cab_p=cab_p,
            discovery=discovery,
            recap=recap,
            emails_template=emails_template,
            campaign_config=campaign_config,
            client_config=client_config,
        )


LOG_PREFIX = "[BYS:Pipeline]"
